mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml         #配置映射文件位置，classpath指resources
  type-aliases-package: com.xspace.ordercenter.dao      #实体类所在位置
  configuration:                                    #打印sql到控制台
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
    helperDialect: mysql                           #分页插件方言选择
    reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: true

