dubbo:
  application:
    name: xspace-order
    environment: develop
  protocol:
    port: 20882
    threadpool: fixed
    threads: 200
    payload: 15728640
  registry:
    address: 192.168.0.141:2181
    file: dubbo-registry-cache/order{replicas.id:}.cache
  provider:
    timeout: 30000
    connections: 5
    group: devGroup
    version: 1.0.0
    retries: 0
  consumer:
    check: false
    group: devGroup


---

spring:
  profiles: test

dubbo:
  registry:
    address: 192.168.0.141:2181

---

spring:
  profiles: local

dubbo:
  registry:
    address: 192.168.0.141