server:
  port: 9888
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.134:3306/trade?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: jsqy
      password: Qyshw_1!
      validationQuery: select 1
      maxActive: 20
      minIdle: 1
      initialSize: 4
      testOnReturn: false
      testWhileIdle: true
      testOnBorrow: true
      logAbandoned: false
      timeBetweenEvictionRunsMillis: 600000
      minEvictableIdleTimeMillis: 600000
      poolPreparedStatements: true
      removeAbandoned: true
      driver-class-name: com.mysql.jdbc.Driver
      name: trade
