package com.xspace.ordercenter.entity;

import java.io.Serializable;

public class TCompanyCountOfBuilding implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.park_code
     *
     * @mbg.generated
     */
    private Integer parkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.park_name
     *
     * @mbg.generated
     */
    private String parkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.build_code
     *
     * @mbg.generated
     */
    private Integer buildCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.build_name
     *
     * @mbg.generated
     */
    private String buildName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.industry_type_code
     *
     * @mbg.generated
     */
    private Byte industryTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.industry_type_name
     *
     * @mbg.generated
     */
    private String industryTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_count_of_building.company_num
     *
     * @mbg.generated
     */
    private Integer companyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company_count_of_building
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.id
     *
     * @return the value of t_company_count_of_building.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.id
     *
     * @param id the value for t_company_count_of_building.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.park_code
     *
     * @return the value of t_company_count_of_building.park_code
     *
     * @mbg.generated
     */
    public Integer getParkCode() {
        return parkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.park_code
     *
     * @param parkCode the value for t_company_count_of_building.park_code
     *
     * @mbg.generated
     */
    public void setParkCode(Integer parkCode) {
        this.parkCode = parkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.park_name
     *
     * @return the value of t_company_count_of_building.park_name
     *
     * @mbg.generated
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.park_name
     *
     * @param parkName the value for t_company_count_of_building.park_name
     *
     * @mbg.generated
     */
    public void setParkName(String parkName) {
        this.parkName = parkName == null ? null : parkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.build_code
     *
     * @return the value of t_company_count_of_building.build_code
     *
     * @mbg.generated
     */
    public Integer getBuildCode() {
        return buildCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.build_code
     *
     * @param buildCode the value for t_company_count_of_building.build_code
     *
     * @mbg.generated
     */
    public void setBuildCode(Integer buildCode) {
        this.buildCode = buildCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.build_name
     *
     * @return the value of t_company_count_of_building.build_name
     *
     * @mbg.generated
     */
    public String getBuildName() {
        return buildName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.build_name
     *
     * @param buildName the value for t_company_count_of_building.build_name
     *
     * @mbg.generated
     */
    public void setBuildName(String buildName) {
        this.buildName = buildName == null ? null : buildName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.industry_type_code
     *
     * @return the value of t_company_count_of_building.industry_type_code
     *
     * @mbg.generated
     */
    public Byte getIndustryTypeCode() {
        return industryTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.industry_type_code
     *
     * @param industryTypeCode the value for t_company_count_of_building.industry_type_code
     *
     * @mbg.generated
     */
    public void setIndustryTypeCode(Byte industryTypeCode) {
        this.industryTypeCode = industryTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.industry_type_name
     *
     * @return the value of t_company_count_of_building.industry_type_name
     *
     * @mbg.generated
     */
    public String getIndustryTypeName() {
        return industryTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.industry_type_name
     *
     * @param industryTypeName the value for t_company_count_of_building.industry_type_name
     *
     * @mbg.generated
     */
    public void setIndustryTypeName(String industryTypeName) {
        this.industryTypeName = industryTypeName == null ? null : industryTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_count_of_building.company_num
     *
     * @return the value of t_company_count_of_building.company_num
     *
     * @mbg.generated
     */
    public Integer getCompanyNum() {
        return companyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_count_of_building.company_num
     *
     * @param companyNum the value for t_company_count_of_building.company_num
     *
     * @mbg.generated
     */
    public void setCompanyNum(Integer companyNum) {
        this.companyNum = companyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_count_of_building
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parkCode=").append(parkCode);
        sb.append(", parkName=").append(parkName);
        sb.append(", buildCode=").append(buildCode);
        sb.append(", buildName=").append(buildName);
        sb.append(", industryTypeCode=").append(industryTypeCode);
        sb.append(", industryTypeName=").append(industryTypeName);
        sb.append(", companyNum=").append(companyNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}