package com.xspace.ordercenter.entity;

import java.io.Serializable;

public class TCompanyIndustry implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_industry.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_industry.company_code
     *
     * @mbg.generated
     */
    private Integer companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company_industry.industry_code
     *
     * @mbg.generated
     */
    private Byte industryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company_industry
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_industry.id
     *
     * @return the value of t_company_industry.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_industry.id
     *
     * @param id the value for t_company_industry.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_industry.company_code
     *
     * @return the value of t_company_industry.company_code
     *
     * @mbg.generated
     */
    public Integer getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_industry.company_code
     *
     * @param companyCode the value for t_company_industry.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(Integer companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company_industry.industry_code
     *
     * @return the value of t_company_industry.industry_code
     *
     * @mbg.generated
     */
    public Byte getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company_industry.industry_code
     *
     * @param industryCode the value for t_company_industry.industry_code
     *
     * @mbg.generated
     */
    public void setIndustryCode(Byte industryCode) {
        this.industryCode = industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_industry
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", industryCode=").append(industryCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}