package com.xspace.ordercenter.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TCompany implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.code
     *
     * @mbg.generated
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.park_code
     *
     * @mbg.generated
     */
    private Integer parkCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.park_name
     *
     * @mbg.generated
     */
    private String parkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.building_code
     *
     * @mbg.generated
     */
    private Integer buildingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.building_name
     *
     * @mbg.generated
     */
    private String buildingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.corporation
     *
     * @mbg.generated
     */
    private String corporation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.registered_capital
     *
     * @mbg.generated
     */
    private Integer registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.longitude
     *
     * @mbg.generated
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.latitude
     *
     * @mbg.generated
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.business_scope
     *
     * @mbg.generated
     */
    private String businessScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.intended_business_code
     *
     * @mbg.generated
     */
    private Byte intendedBusinessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.industry_type_code
     *
     * @mbg.generated
     */
    private Byte industryTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_company
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.id
     *
     * @return the value of t_company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.id
     *
     * @param id the value for t_company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.code
     *
     * @return the value of t_company.code
     *
     * @mbg.generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.code
     *
     * @param code the value for t_company.code
     *
     * @mbg.generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.park_code
     *
     * @return the value of t_company.park_code
     *
     * @mbg.generated
     */
    public Integer getParkCode() {
        return parkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.park_code
     *
     * @param parkCode the value for t_company.park_code
     *
     * @mbg.generated
     */
    public void setParkCode(Integer parkCode) {
        this.parkCode = parkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.park_name
     *
     * @return the value of t_company.park_name
     *
     * @mbg.generated
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.park_name
     *
     * @param parkName the value for t_company.park_name
     *
     * @mbg.generated
     */
    public void setParkName(String parkName) {
        this.parkName = parkName == null ? null : parkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.building_code
     *
     * @return the value of t_company.building_code
     *
     * @mbg.generated
     */
    public Integer getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.building_code
     *
     * @param buildingCode the value for t_company.building_code
     *
     * @mbg.generated
     */
    public void setBuildingCode(Integer buildingCode) {
        this.buildingCode = buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.building_name
     *
     * @return the value of t_company.building_name
     *
     * @mbg.generated
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.building_name
     *
     * @param buildingName the value for t_company.building_name
     *
     * @mbg.generated
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.company_name
     *
     * @return the value of t_company.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.company_name
     *
     * @param companyName the value for t_company.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.corporation
     *
     * @return the value of t_company.corporation
     *
     * @mbg.generated
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.corporation
     *
     * @param corporation the value for t_company.corporation
     *
     * @mbg.generated
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.create_date
     *
     * @return the value of t_company.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.create_date
     *
     * @param createDate the value for t_company.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.registered_capital
     *
     * @return the value of t_company.registered_capital
     *
     * @mbg.generated
     */
    public Integer getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.registered_capital
     *
     * @param registeredCapital the value for t_company.registered_capital
     *
     * @mbg.generated
     */
    public void setRegisteredCapital(Integer registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.address
     *
     * @return the value of t_company.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.address
     *
     * @param address the value for t_company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.phone_number
     *
     * @return the value of t_company.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.phone_number
     *
     * @param phoneNumber the value for t_company.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.longitude
     *
     * @return the value of t_company.longitude
     *
     * @mbg.generated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.longitude
     *
     * @param longitude the value for t_company.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.latitude
     *
     * @return the value of t_company.latitude
     *
     * @mbg.generated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.latitude
     *
     * @param latitude the value for t_company.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.business_scope
     *
     * @return the value of t_company.business_scope
     *
     * @mbg.generated
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.business_scope
     *
     * @param businessScope the value for t_company.business_scope
     *
     * @mbg.generated
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.intended_business_code
     *
     * @return the value of t_company.intended_business_code
     *
     * @mbg.generated
     */
    public Byte getIntendedBusinessCode() {
        return intendedBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.intended_business_code
     *
     * @param intendedBusinessCode the value for t_company.intended_business_code
     *
     * @mbg.generated
     */
    public void setIntendedBusinessCode(Byte intendedBusinessCode) {
        this.intendedBusinessCode = intendedBusinessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_company.industry_type_code
     *
     * @return the value of t_company.industry_type_code
     *
     * @mbg.generated
     */
    public Byte getIndustryTypeCode() {
        return industryTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_company.industry_type_code
     *
     * @param industryTypeCode the value for t_company.industry_type_code
     *
     * @mbg.generated
     */
    public void setIndustryTypeCode(Byte industryTypeCode) {
        this.industryTypeCode = industryTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", parkCode=").append(parkCode);
        sb.append(", parkName=").append(parkName);
        sb.append(", buildingCode=").append(buildingCode);
        sb.append(", buildingName=").append(buildingName);
        sb.append(", companyName=").append(companyName);
        sb.append(", corporation=").append(corporation);
        sb.append(", createDate=").append(createDate);
        sb.append(", registeredCapital=").append(registeredCapital);
        sb.append(", address=").append(address);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", businessScope=").append(businessScope);
        sb.append(", intendedBusinessCode=").append(intendedBusinessCode);
        sb.append(", industryTypeCode=").append(industryTypeCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}