package com.xspace.ordercenter.entity;

import java.io.Serializable;

public class TGridManager implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.code
     *
     * @mbg.generated
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.area_code
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.grid_code
     *
     * @mbg.generated
     */
    private String gridCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.grid_name
     *
     * @mbg.generated
     */
    private String gridName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grid_manager.logo_src
     *
     * @mbg.generated
     */
    private String logoSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_grid_manager
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.id
     *
     * @return the value of t_grid_manager.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.id
     *
     * @param id the value for t_grid_manager.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.code
     *
     * @return the value of t_grid_manager.code
     *
     * @mbg.generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.code
     *
     * @param code the value for t_grid_manager.code
     *
     * @mbg.generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.name
     *
     * @return the value of t_grid_manager.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.name
     *
     * @param name the value for t_grid_manager.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.sex
     *
     * @return the value of t_grid_manager.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.sex
     *
     * @param sex the value for t_grid_manager.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.area_code
     *
     * @return the value of t_grid_manager.area_code
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.area_code
     *
     * @param areaCode the value for t_grid_manager.area_code
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.area_name
     *
     * @return the value of t_grid_manager.area_name
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.area_name
     *
     * @param areaName the value for t_grid_manager.area_name
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.mobile
     *
     * @return the value of t_grid_manager.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.mobile
     *
     * @param mobile the value for t_grid_manager.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.grid_code
     *
     * @return the value of t_grid_manager.grid_code
     *
     * @mbg.generated
     */
    public String getGridCode() {
        return gridCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.grid_code
     *
     * @param gridCode the value for t_grid_manager.grid_code
     *
     * @mbg.generated
     */
    public void setGridCode(String gridCode) {
        this.gridCode = gridCode == null ? null : gridCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.grid_name
     *
     * @return the value of t_grid_manager.grid_name
     *
     * @mbg.generated
     */
    public String getGridName() {
        return gridName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.grid_name
     *
     * @param gridName the value for t_grid_manager.grid_name
     *
     * @mbg.generated
     */
    public void setGridName(String gridName) {
        this.gridName = gridName == null ? null : gridName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grid_manager.logo_src
     *
     * @return the value of t_grid_manager.logo_src
     *
     * @mbg.generated
     */
    public String getLogoSrc() {
        return logoSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grid_manager.logo_src
     *
     * @param logoSrc the value for t_grid_manager.logo_src
     *
     * @mbg.generated
     */
    public void setLogoSrc(String logoSrc) {
        this.logoSrc = logoSrc == null ? null : logoSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grid_manager
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", areaName=").append(areaName);
        sb.append(", mobile=").append(mobile);
        sb.append(", gridCode=").append(gridCode);
        sb.append(", gridName=").append(gridName);
        sb.append(", logoSrc=").append(logoSrc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}