package com.xspace.ordercenter.entity;

import java.io.Serializable;

public class TIndustryType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industry_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industry_type.code
     *
     * @mbg.generated
     */
    private Byte code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industry_type.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industry_type.parent_code
     *
     * @mbg.generated
     */
    private Byte parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industry_type.level
     *
     * @mbg.generated
     */
    private Boolean level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_industry_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industry_type.id
     *
     * @return the value of t_industry_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industry_type.id
     *
     * @param id the value for t_industry_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industry_type.code
     *
     * @return the value of t_industry_type.code
     *
     * @mbg.generated
     */
    public Byte getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industry_type.code
     *
     * @param code the value for t_industry_type.code
     *
     * @mbg.generated
     */
    public void setCode(Byte code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industry_type.name
     *
     * @return the value of t_industry_type.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industry_type.name
     *
     * @param name the value for t_industry_type.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industry_type.parent_code
     *
     * @return the value of t_industry_type.parent_code
     *
     * @mbg.generated
     */
    public Byte getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industry_type.parent_code
     *
     * @param parentCode the value for t_industry_type.parent_code
     *
     * @mbg.generated
     */
    public void setParentCode(Byte parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industry_type.level
     *
     * @return the value of t_industry_type.level
     *
     * @mbg.generated
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industry_type.level
     *
     * @param level the value for t_industry_type.level
     *
     * @mbg.generated
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industry_type
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", parentCode=").append(parentCode);
        sb.append(", level=").append(level);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}