package com.xspace.ordercenter.entity;

import java.io.Serializable;

public class TManagerCompanyRecommend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_company_recommend.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_company_recommend.manager_code
     *
     * @mbg.generated
     */
    private Integer managerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_company_recommend.company_code
     *
     * @mbg.generated
     */
    private Integer companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_company_recommend.our_ratings
     *
     * @mbg.generated
     */
    private Byte ourRatings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_manager_company_recommend
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_company_recommend.id
     *
     * @return the value of t_manager_company_recommend.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_company_recommend.id
     *
     * @param id the value for t_manager_company_recommend.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_company_recommend.manager_code
     *
     * @return the value of t_manager_company_recommend.manager_code
     *
     * @mbg.generated
     */
    public Integer getManagerCode() {
        return managerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_company_recommend.manager_code
     *
     * @param managerCode the value for t_manager_company_recommend.manager_code
     *
     * @mbg.generated
     */
    public void setManagerCode(Integer managerCode) {
        this.managerCode = managerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_company_recommend.company_code
     *
     * @return the value of t_manager_company_recommend.company_code
     *
     * @mbg.generated
     */
    public Integer getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_company_recommend.company_code
     *
     * @param companyCode the value for t_manager_company_recommend.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(Integer companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_company_recommend.our_ratings
     *
     * @return the value of t_manager_company_recommend.our_ratings
     *
     * @mbg.generated
     */
    public Byte getOurRatings() {
        return ourRatings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_company_recommend.our_ratings
     *
     * @param ourRatings the value for t_manager_company_recommend.our_ratings
     *
     * @mbg.generated
     */
    public void setOurRatings(Byte ourRatings) {
        this.ourRatings = ourRatings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_company_recommend
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", managerCode=").append(managerCode);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", ourRatings=").append(ourRatings);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}