package com.xspace.ordercenter.entity;

import java.io.Serializable;

public class TPark implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.grid_code
     *
     * @mbg.generated
     */
    private String gridCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.manager_code
     *
     * @mbg.generated
     */
    private Integer managerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.city_code
     *
     * @mbg.generated
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.area_code
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.building_num
     *
     * @mbg.generated
     */
    private Integer buildingNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park.logo_src
     *
     * @mbg.generated
     */
    private String logoSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_park
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.id
     *
     * @return the value of t_park.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.id
     *
     * @param id the value for t_park.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.grid_code
     *
     * @return the value of t_park.grid_code
     *
     * @mbg.generated
     */
    public String getGridCode() {
        return gridCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.grid_code
     *
     * @param gridCode the value for t_park.grid_code
     *
     * @mbg.generated
     */
    public void setGridCode(String gridCode) {
        this.gridCode = gridCode == null ? null : gridCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.manager_code
     *
     * @return the value of t_park.manager_code
     *
     * @mbg.generated
     */
    public Integer getManagerCode() {
        return managerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.manager_code
     *
     * @param managerCode the value for t_park.manager_code
     *
     * @mbg.generated
     */
    public void setManagerCode(Integer managerCode) {
        this.managerCode = managerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.code
     *
     * @return the value of t_park.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.code
     *
     * @param code the value for t_park.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.name
     *
     * @return the value of t_park.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.name
     *
     * @param name the value for t_park.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.city_code
     *
     * @return the value of t_park.city_code
     *
     * @mbg.generated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.city_code
     *
     * @param cityCode the value for t_park.city_code
     *
     * @mbg.generated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.city_name
     *
     * @return the value of t_park.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.city_name
     *
     * @param cityName the value for t_park.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.area_code
     *
     * @return the value of t_park.area_code
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.area_code
     *
     * @param areaCode the value for t_park.area_code
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.area_name
     *
     * @return the value of t_park.area_name
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.area_name
     *
     * @param areaName the value for t_park.area_name
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.address
     *
     * @return the value of t_park.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.address
     *
     * @param address the value for t_park.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.building_num
     *
     * @return the value of t_park.building_num
     *
     * @mbg.generated
     */
    public Integer getBuildingNum() {
        return buildingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.building_num
     *
     * @param buildingNum the value for t_park.building_num
     *
     * @mbg.generated
     */
    public void setBuildingNum(Integer buildingNum) {
        this.buildingNum = buildingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park.logo_src
     *
     * @return the value of t_park.logo_src
     *
     * @mbg.generated
     */
    public String getLogoSrc() {
        return logoSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park.logo_src
     *
     * @param logoSrc the value for t_park.logo_src
     *
     * @mbg.generated
     */
    public void setLogoSrc(String logoSrc) {
        this.logoSrc = logoSrc == null ? null : logoSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gridCode=").append(gridCode);
        sb.append(", managerCode=").append(managerCode);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", cityName=").append(cityName);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", areaName=").append(areaName);
        sb.append(", address=").append(address);
        sb.append(", buildingNum=").append(buildingNum);
        sb.append(", logoSrc=").append(logoSrc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}