server:
  port: 18188

spring:
  profiles:
    active: dev



logging:
  file: /home/web/logs/

#生產和消費者配製
dubbo:
  application:
    name: market-service
    environment: develop
  protocol:
    port: 20880
    threadpool: fixed
    threads: 200
  registry:
    address: 192.168.0.131:2181,192.168.0.132:2181,192.168.0.133:2181
    file: dubbo-registry-cache/market${replicas.id:}.cache
  provider:
    timeout: 30000
    connections: 5
    group: devGroup
    version: 1.0.0
    retries: 0
  consumer:
    check: false
    group: devGroup

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.0.134:3306/es_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1429425727
dubbo:
  registry:
    address: 192.168.0.131:2181,192.168.0.132:2181,192.168.0.133:2181

