package com.xspace.ordercenter.dao;

import com.xspace.ordercenter.entity.Employee;
import com.xspace.ordercenter.req.EmployeeDto;

import java.util.List;


public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer employeeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    Employee selectByPrimaryKey(Integer employeeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    List<Employee> selectAll();
    List<EmployeeDto> selectA();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Employee record);
}