package com.xspace.ordercenter.dao;



import com.xspace.ordercenter.entity.TBuilding;
import com.xspace.ordercenter.rsp.BuildingIndustryStatRsp;

import java.util.List;

public interface TBuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbg.generated
     */
    int insert(TBuilding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbg.generated
     */
    TBuilding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbg.generated
     */
    List<TBuilding> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBuilding record);

    List<BuildingIndustryStatRsp> buildingList(String parkCode);
}