package com.xspace.ordercenter.dao;



import com.unicom.js.ibo.infocenter.bean.TBusiness;

import java.util.List;

public interface TBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int insert(TBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    TBusiness selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    List<TBusiness> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBusiness record);
}