package com.xspace.ordercenter.dao;





import com.xspace.ordercenter.entity.TCompanyIndustry;

import java.util.List;

public interface TCompanyIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_industry
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_industry
     *
     * @mbg.generated
     */
    int insert(TCompanyIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_industry
     *
     * @mbg.generated
     */
    TCompanyIndustry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_industry
     *
     * @mbg.generated
     */
    List<TCompanyIndustry> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_industry
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCompanyIndustry record);
}