package com.xspace.ordercenter.dao;



import com.xspace.ordercenter.bean.TGridManager;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TGridManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grid_manager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grid_manager
     *
     * @mbg.generated
     */
    int insert(TGridManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grid_manager
     *
     * @mbg.generated
     */
    TGridManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grid_manager
     *
     * @mbg.generated
     */
    List<TGridManager> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grid_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TGridManager record);
    TGridManager findByMobile(@Param("mobile") String  mobile);
}