package com.xspace.ordercenter.dao;



import com.unicom.js.ibo.infocenter.bean.TManagerCompanyRecommend;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public interface TManagerCompanyRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_company_recommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_company_recommend
     *
     * @mbg.generated
     */
    int insert(TManagerCompanyRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_company_recommend
     *
     * @mbg.generated
     */
    TManagerCompanyRecommend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_company_recommend
     *
     * @mbg.generated
     */
    List<TManagerCompanyRecommend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_company_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TManagerCompanyRecommend record);

    ArrayList<String> findHotCompanyIds(Map<String, Object> queryParam);
}