package com.xspace.ordercenter.dao;


import com.xspace.ordercenter.entity.TPark;
import com.xspace.ordercenter.req.SearchParkReq;
import com.xspace.ordercenter.rsp.SearchParkRsp;

import java.util.List;
import java.util.Map;

public interface TParkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park
     *
     * @mbg.generated
     */
    int insert(TPark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park
     *
     * @mbg.generated
     */
    TPark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park
     *
     * @mbg.generated
     */
    List<TPark> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPark record);

    List<SearchParkRsp> findParkList(Map<String, Object> queryParam);

    List<SearchParkRsp> searchPark(SearchParkReq req);
}